### ISSUE TITLE
which GeoLite dataset?

### ISSUE THREAD

**Issue by jbenet** [ipfs-shipyard/ipfs-geoip#2]
the readme says to generate the tree from `path/GeoLite-Blocks.csv`, but it's not clear which one? the page http://dev.maxmind.com/geoip/legacy/geolite/ lists several possibilities?

Would be good to include a mapping (on the readme or another file) of:
- the original import csv (src url + IPFS url -- let's back it up!) 
- the generated geo-ip tree root

that way we can make sure to back them all up as we increase versions. 

maybe the list of refs can be -- itself -- an ipfs node. that way we can just back up that root to backup all versions ever. (( we need to come up with a good way of doing this that's friendly with git, github, and ipfs  -- i've been using "published-version" files, but this isn't the best thing ever))

**Comment by krl** [comment]
I saw you comment somewhere else about moving this to the ipfs org, i agree.

However, i would also like to take some time to update this to the latest version and provide tooling for easier updating and (maybe later) structural sharing of the non-changing parts.

**Comment by jbenet** [comment]
sounds good. though you can do that in the ipfs org too (like, you should continue being the maintainer)

**Comment by daviddias** [comment]
Hey @krl, can we get an update on Juan's question? ty :)

**Comment by krl** [comment]
I was using GeoLiteCity_20150407

I would like to re-write this into a structure that handles updates better, ie. doing rabin-fingerprint-style splitting of the b-tree, so that we can keep this up to date more easily.

**Comment by krl** [comment]
I'm surprised this disappeared though, since pinbot was on it?

**Comment by krl** [comment]
https://ipfs.io/ipfs/QmZAKL5VV2suFpTMgJBevEx5WvAgerjh9oF1wU6fyqbS5r

**Comment by lidel** [comment]
Continued in https://github.com/ipfs-shipyard/ipfs-geoip/issues/68
