### ISSUE TITLE
Move to ipfs-shipyard?

### ISSUE THREAD

**Issue by daviddias** [ipfs-shipyard/ipfs-geoip#58]
Now we have an org to incubate projects that not part of the core implementation of the protocol or discussion of the spec. That org is [ipfs-shipyard](https://github.com/ipfs-shipyard) created from https://github.com/ipfs/pm/issues/448

Short description:
> IPFS Shipyard is a venue for the community to pursue and collaborate on research experiments, products, code libraries and more around the IPFS project. It is where innovation in userland happens and where we discover and form new primitives to push to the core of IPFS.

Anyone opposing?

**Comment by dignifiedquire** [comment]
Why? This is part of webui and as such shipped with every release of go-ipfs

**Comment by victorb** [comment]
@dignifiedquire we should still be able to ship this as part with webui, even if it's with ipfs-shipyard

**Comment by dignifiedquire** [comment]
Sure, but it is part of the core offering is what I am trying to say. So I don't see the reason to move it to the shipyard

**Comment by daviddias** [comment]
It can stay here :)
