### ISSUE TITLE
Some new ideas  about LBP by geohash and ipfs

### ISSUE THREAD

**Issue by daijiale** [ipfs-shipyard/ipfs-geoip#64]
Thanks to this perfect project , it made me came up with some new ideas ！

 I have making a research about a geography relation object model demo with geohash and ipfs,
here are some of my work ,maybe there will be some location base service (LBP) application condition for IPFS :[https://github.com/daijiale/ipfs-geo](https://github.com/daijiale/ipfs-geo)

expect to communicate with you

**Comment by hsanjuan** [comment]
Thanks. Please follow up in https://discuss.ipfs.io if you have any other news.
