### ISSUE TITLE
Support for domain names ?

### ISSUE THREAD

**Issue by lazyweirdo** [ipfs-shipyard/ipfs-geoip#73]
i mean, could we run something like the following command ?

`node index.js ipfs.io`

Is it supported ? ... is it even possible ? it would be nice to use it here https://github.com/ipfs/public-gateway-checker

**Comment by lidel** [comment]
While this does not belong to this project (it operates on raw IPs), if anyone is looking for a solution that works in the browser, @lazyweirdo  solved this  in https://github.com/lazyweirdo/public-gateway-checker/blob/4712bd274289255352a09e1e7c7937ee2925b8be/app.js#L207-L222
