### ISSUE TITLE
Previous Data

### ISSUE THREAD

**Issue by RichardLitt** [ipfs-shipyard/ipfs-geoip#8]
@jbenet [here](https://github.com/ipfs/weekly/pull/17#discussion_r55001329):

>  [geoip lookups] should work in previous releases too. we should be able to regenerate the exact data. the database has versions. so does the codebase.

Is there any way we can do this?

**Comment by lidel** [comment]
We've switched to DAG-CBOR in https://github.com/ipfs-shipyard/ipfs-geoip/pull/93 which makes things bit more future-proof. 
As long b-tree generation logic remains the same, one can switch `DATA_HASH` in `src/generate/index.js` to a previos snapshot and get the same CID.
